# ------------------------------------------------------------------------------
# Defines the main window of the Shakespeare AI application created in PyQt5.
# ------------------------------------------------------------------------------

from PyQt5 import QtWidgets, QtGui, QtCore
from convai import convai
from gemini import gemini
import os, sys

# ------------------------------------------------------------------------------
# The ShakespeareWindow class is used to create 
# the main window of the Shakespeare AI application 
# and it inherits from QMainWindow.
# ------------------------------------------------------------------------------

class ShakespeareWindow(QtWidgets.QMainWindow):
    '''
    Main window meant for interacting with the Shakespeare AI.
    It makes calls to the convai and gemini backend,
    to process the image and start the conversation.
    '''
    def __init__(self):
        '''
        Initializes the main window, sets up the UI.
        '''
        super().__init__()
        self.convaiBackend = None
        self.initUI()     

    def initUI(self):
        '''
        First initializes the window, 
        then the layouts, then the individual components.
        '''
        self.initWindow()
        self.initLayouts()
        self.initComponents()
        self.applyOvStylesheet() # using a custom stylesheet
                                 # to mimic Omniverse's theme
    def initWindow(self):
        '''
        Set up window specific properties.
        '''
        self.setWindowTitle('Shakespeare AI')
        basePath = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
        self.setWindowIcon(QtGui.QIcon(os.path.join(basePath, 'misc/sp_logo.png')))
        self.setFixedSize(400, 500)
        self.show()

    def initLayouts(self):
        '''
        Set up the various layouts for the components.
        '''
        self.centralWidget = QtWidgets.QWidget()
        self.setCentralWidget(self.centralWidget)
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralWidget)

    def initComponents(self):
        '''
        Set up the individual components of the window.
        '''
        self.initBtns()
        self.initImgHolder()
        self.initStatusBar()

    def initBtns(self):
        '''
        Set up the buttons for selecting the image, starting the conversation,
        '''
        self.btnLayout = QtWidgets.QHBoxLayout()
        self.mainLayout.addLayout(self.btnLayout)

        self.selectImgBtn = QtWidgets.QPushButton('Select Image')
        self.btnLayout.addWidget(self.selectImgBtn)
        self.selectImgBtn.clicked.connect(self.selectImg)

        self.convaiBtn = QtWidgets.QPushButton('Start Talking')
        self.btnLayout.addWidget(self.convaiBtn)
        self.convaiBtn.clicked.connect(self.onConvaiBtnClick)

        self.stopBtnLayout = QtWidgets.QHBoxLayout()
        self.mainLayout.addLayout(self.stopBtnLayout)

        self.stopSpBtn = QtWidgets.QPushButton('Stop Shakespeare')
        self.stopBtnLayout.addWidget(self.stopSpBtn)
        self.stopSpBtn.clicked.connect(self.onStopSpBtnClick)
        self.stopSpBtn.setEnabled(False)  

    def initImgHolder(self):
        '''
        Set up the image holder to display the selected image.
        '''
        self.imgGb = QtWidgets.QGroupBox('Selected Image')
        self.imgGb.setLayout(QtWidgets.QVBoxLayout())

        self.imgLabel = QtWidgets.QLabel()
        self.imgLabel.setFixedSize(340, 300)
        self.imgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imgLabel.setScaledContents(False)

        self.imgGb.layout().addWidget(self.imgLabel)
        self.mainLayout.addWidget(self.imgGb)

    def initStatusBar(self):
        '''
        Status bar to show messages to the user.
        '''
        self.statusBar = QtWidgets.QStatusBar()  
        self.setStatusBar(self.statusBar)
        self.statusBar.showMessage('Ready', 5000) 

    def selectImg(self):
        ''''
        Opens a file dialog to select an image.
        '''
        fName, _ = QtWidgets.QFileDialog.getOpenFileName(self, 'Select Image', '',
                                                      'Images (*.jpg *.jpeg *.png *.heic *.heif)')
        if fName:
            self.processImg(fName)

    def processImg(self, imgPath):
        '''
        Loads, displays the image and gets the response from the gemini backend.
        Then appends the responnse generated by gemini to the character's context window.
        '''
        pixmap = QtGui.QPixmap(imgPath)

        if not pixmap.isNull():
            pixmap = pixmap.scaled(self.imgLabel.size(), QtCore.Qt.KeepAspectRatio,
                                 QtCore.Qt.SmoothTransformation)
            self.imgLabel.setPixmap(pixmap)
            self.geminiResponse = gemini.getGeminiResponse(imgPath)
            self.showMsg('Talk to Shakespeare about this image!')
            convai.appendToCharBackstory(self.geminiResponse)

    def onConvaiBtnClick(self):
        '''
        Connects the window to the convai backend upon button click.
        '''
        if self.convaiBackend is None:
            self.convaiBackend = convai.ConvaiBackend.getInstance()
            self.connectEventsToConvai() # to update the UI based on 
                                         # the backend's state
        if self.convaiBackend.isCapturingAudio:
            self.convaiBackend.stopConvai()
        else:
            self.convaiBackend.startConvai()

    def onStopSpBtnClick(self):
        '''
        Stops the conversation with Shakespeare.
        '''
        if self.convaiBackend is not None:
            self.convaiBackend.stopShakespeare()

    def connectEventsToConvai(self):
        self.convaiBackend.updateBtnTextSignal.connect(self.convaiBtn.setText)
        self.convaiBackend.setBtnEnabledSignal.connect(self.convaiBtn.setEnabled) 
        self.convaiBackend.stateChangeSignal.connect(self.handleConvaiStateChange)
        self.convaiBackend.errorSignal.connect(self.showMsg)
        self.convaiBackend.isSendingAudSignal.connect(self.updateStopButtonState)

    def handleConvaiStateChange(self, isTalking):
        if isTalking:
            self.statusBar.showMessage('Shakespeare started speaking!', 5000)
        else:
            self.statusBar.showMessage('Shakespeare stopped speaking', 5000)

    def updateStopButtonState(self, isSendingAudio):
        self.stopSpBtn.setEnabled(isSendingAudio)

    def showMsg(self, msg):
        '''
        Shows a message in the status bar for 5 seconds.
        '''
        self.statusBar.showMessage(msg, 50000) 

    def applyOvStylesheet(self):
        '''
        Applies a custom stylesheet to mimic Omniverse's theme.
        '''
        stylesheet = '''
        QMainWindow {
            background-color: #454444;
            color: white;
        }
        QPushButton {
            background-color: #282829;
            color: white;
            border: 1px solid #555555;
            padding: 5px;
        }
        QPushButton:hover {
            background-color: #555555;
        }
        QLabel {
            color: white;
        }
        QGroupBox {
            border: 1px solid #555555;
            margin-top: 10px;
            padding: 10px;
            color: white;
        }
        QStatusBar {
            background-color: #454444;
            color: white;
        }
        '''
        self.setStyleSheet(stylesheet)

if __name__ == '__main__': # for testing
    app = QtWidgets.QApplication(sys.argv)
    ex = ShakespeareWindow()
    sys.exit(app.exec_())